# bookdown组件

本章内容包括在使用模板撰写论文时常用的bookdown组件，包括代码块、图片、表格、引用、数学定理与方程。本章的大部分内容翻译自https://bookdown.org/yihui/bookdown/components.html。由于bookdown的建立是基于pandoc的，我们从一些pandoc语法开始。

## markdown语法

### 行内样式

你可以通过`_斜体_`或`*斜体*`来使用*斜体*；用`**粗体**`或`__粗体__`来使用**粗体**。两个`~`中间的文字会变为下标如`X~1~,X~2~,\cdots,X~n~`，会生成X~1~,X~2~,\cdots,X~n~；同样俩个`^`间的文字会变为上标如`X^2^`会生成X^2^。超链接将使用`[text](link)`创建，如`[RStudio](https://www.rstudio.com)`[RStudio](https://www.rstudio.com)。可以使用`^[]`添加脚注，如`^[这是一个脚注]`^[这是一个脚注]

### 数学表达式

你可以在一对`$`中间插入行内LaTex数学表达式，例如`$f(k) = {n \choose k} p^{k} (1-p)^{n-k}$`会输出$f(k) = {n \choose k} p^{k} (1-p)^{n-k}$，或者在一对`$$`中插入行间数学表达式，例如`$$f(k) = {n \choose k} p^{k} (1-p)^{n-k}$$` 会输出 $$f(k) = {n \choose k} p^{k} (1-p)^{n-k}$$。

同样，你还可以在`$ $`或`$$ $$`中间使用其他数学环境，比如
```
$$\begin{array}{ccc}
x_{11} & x_{12} & x_{13}\\
x_{21} & x_{22} & x_{23}
\end{array}$$
```
$$\begin{array}{ccc}
x_{11} & x_{12} & x_{13}\\
x_{21} & x_{22} & x_{23}
\end{array}$$

你可以引用更多的数学环境如矩阵、行列式等等，详情可以参考latex中文简介

## bookdown支持的markdown拓展

为了有效的给数学公式标数字且引用，你可以在公式的数学环境中加入标签`(\#eq:标签)`，并引用他们，例如：

```
\begin{equation} 
  f\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k}
  (\#eq:binom)
\end{equation}
```
将得到：
$$
\begin{equation} 
  f\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k}
  (\#eq:binom)
\end{equation}
$$
那么你就可以使用`\@ref(eq:binom)`来引用此公式，例如见\@ref(eq:binom)

## 定理与证明{#theorems-proof}

bookdown中支持另一种定理环境，是基于code chunk来完成的，例如
```
```{theorem}
这是一条定理
```
```
输出结果为：
```{theorem}
这是一条定理
```
在theorem环境中你还可以设置另外两个参数`name=''`和`label=''`，他们分别定义了theorem环境的定理名称和引用标签，例如：
```
```{theorem, label='pyth', name="勾股定理"}

对于一个直角三角形，如果 $c$三角形的斜边而 $a$和 $b$分别为三角形的直角边，则有：
$$a^2 + b^2 = c^2$$
```
```
在引用时你可以使用`\@ref(prefix:label)`，prefix是定理环境的简写，对于theorem为thm，那么我们要引用此定理，就可以用`\@ref(thm:pyth)`，即，见定理\@ref(thm:pyth)

对于更多的定理环境以及他们对应的prefix可以见[theorems](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#theorems)。



## 图片

你可以通过knitr来输出图片并加载至文章中：

```{r}
par(mar = c(4, 4, 0.1, 0.1))
plot(pressure, pch = 19, type = "b")
```

当然，在使用LaTex制作论文并插入图片时，你几乎不可避免的会遇到图片浮动的问题，即图片可能会出现在文章的其他位置。如果你不常使用LaTex并且不希望这种情况发生，你应该注意图片的浮动问题，通过修改图片的尺寸来解决这个问题。

